[Data.Transformation.Filter]
# Valeurs minimales et maximales de latitude et longitude pour filtrer les données {int, float}.
# Commenter les lignes suivantes pour utiliser les valeurs par défaut.
min_latitude = -90
max_latitude = 90
min_longitude = -180
max_longitude = 180
# Valeurs minimales et maximales de profondeur pour filtrer les données {int, float}
min_depth = 0
# Ce paramètre est désactivé par défaut.
# max_depth = 1000