"""
Ce module contient les constantes utilisées pour parser les données des fichiers OFM, DCDB, Lowrance et Actisense.
"""

# Constantes pour les noms des colonnes des données OFM et DCDB.
LONGITUDE_DCDB: str = "LON"
"""Valeur de la constante pour la colonne de longitude des données DCDB."""
LATITUDE_DCDB: str = "LAT"
"""Valeur de la constante pour la colonne de latitude des données DCDB."""
DEPTH_DCDB: str = "DEPTH"
"""Valeur de la constante pour la colonne de profondeur des données DCDB."""
TIME: str = "TIME"
"""Valeur de la constante pour la colonne de temps des données DCDB."""

# Constantes pour les noms des colonnes des données Lowrance.
LONGITUDE_LOWRANCE: str = "Longitude[°WGS84]"
"""Valeur de la constante pour la colonne de longitude des données Lowrance."""
LATITUDE_LOWRANCE: str = "Latitude[°WGS84]"
"""Valeur de la constante pour la colonne de latitude des données Lowrance."""
DEPTH_LOWRANCE: str = "WaterDepth[Feet]"
"""Valeur de la constante pour la colonne de profondeur des données Lowrance."""
TIME_LOWRANCE: str = "DateTime[UTC]"
"""Valeur de la constante pour la colonne de temps des données Lowrance."""

# Constantes pour les noms des colonnes des données Actisense.
LINE_ACTISENSE: str = "Line"
"""Valeur de la constante pour la colonne de ligne des données Actisense."""
TIME_ACTISENSE: str = "Time"
"""Valeur de la constante pour la colonne de temps des données Actisense."""
NAME_ACTISENSE: str = "Name"
"""Valeur de la constante pour la colonne de nom des données Actisense."""
DEPTH_ACTISENSE: str = "Water Depth Transducer"
"""Valeur de la constante pour la colonne de profondeur des données Actisense."""
OFFSET_ACTISENSE: str = "Offset"
"""Valeur de la constante pour la colonne de décalage des données Actisense."""
POSITION_DATE_ACTISENSE: str = "Position date"
"""Valeur de la constante pour la colonne de date de position des données Actisense."""
POSITION_TIME_ACTISENSE: str = "Position time"
"""Valeur de la constante pour la colonne de temps de position des données Actisense."""
LATITUDE_ACTISENSE: str = "Latitude.1"
"""Valeur de la constante pour la colonne de latitude des données Actisense."""
LONGITUDE_ACTISENSE: str = "Longitude.1"
"""Valeur de la constante pour la colonne de longitude des données Actisense."""
COURSE_OVER_GROUND_ACTISENSE: str = "Course Over Ground"
"""Valeur de la constante pour la colonne de cap sur le fond des données Actisense."""
SPEED_OVER_GROUND_ACTISENSE: str = "Speed Over Ground"
"""Valeur de la constante pour la colonne de vitesse sur le fond des données Actisense."""
PGN_ACTISENSE: str = "PGN"
"""Valeur de la constante pour la colonne de PGN des données Actisense."""

# Constantes pour les dtypes des données.
FLOAT64: str = "float64"
"""Valeur de la constante pour le type de données float64."""
EPSG_WGS84: str = "EPSG:4326"
"""Valeur de la constante pour le code EPSG 4326."""
