"""
Ce module contient les constantes utilisées pour parser les données des fichiers OFM, DCDB, Lowrance et Actisense.
"""

# Constantes pour les noms des colonnes des données DCDB.
DCDB: str = "DCDB"
"""Valeur de la constante pour le type de données DCDB."""
LONGITUDE_DCDB: str = "LON"
"""Valeur de la constante pour la colonne de longitude des données DCDB."""
LATITUDE_DCDB: str = "LAT"
"""Valeur de la constante pour la colonne de latitude des données DCDB."""
DEPTH_DCDB: str = "DEPTH"
"""Valeur de la constante pour la colonne de profondeur des données DCDB."""
TIME_DCDB: str = "TIME"
"""Valeur de la constante pour la colonne de temps des données DCDB."""

# Constantes pour les noms des colonnes des données OFM.
OFM: str = "OFM"
"""Valeur de la constante pour le type de données OFM."""
LONGITUDE_OFM: str = "LON"
"""Valeur de la constante pour la colonne de longitude des données OFM."""
LATITUDE_OFM: str = "LAT"
"""Valeur de la constante pour la colonne de latitude des données OFM."""
DEPTH_OFM: str = "DEPTH"
"""Valeur de la constante pour la colonne de profondeur des données OFM."""
TIME_OFM: str = "TIME"
"""Valeur de la constante pour la colonne de temps des données OFM."""
TIMESTAMP_OFM: str = "TimeStamp"
"""Valeur de la constante pour la colonne de timestamp des données OFM."""

# Constantes pour les noms des colonnes des données Lowrance.
LOWRANCE: str = "Lowrance"
"""Valeur de la constante pour le type de données Lowrance."""
LONGITUDE_LOWRANCE: str = "Longitude[°WGS84]"
"""Valeur de la constante pour la colonne de longitude des données Lowrance."""
LATITUDE_LOWRANCE: str = "Latitude[°WGS84]"
"""Valeur de la constante pour la colonne de latitude des données Lowrance."""
DEPTH_LOWRANCE: str = "WaterDepth[Feet]"
"""Valeur de la constante pour la colonne de profondeur des données Lowrance."""
TIME_LOWRANCE: str = "DateTime[UTC]"
"""Valeur de la constante pour la colonne de temps des données Lowrance."""
SURVEY_TYPE_LOWRANCE: str = "SurveyType"
"""Valeur de la constante pour la colonne de type de relevé des données Lowrance."""
PRIMARY_LOWRANCE: str = "Primary"
"""Valeur de la constante pour le type de relevé primaire des données Lowrance."""
SPEED_LOWRANCE: str = "GNSSSpeed[m/s]"
"""Valeur de la constante pour la colonne de vitesse des données Lowrance."""

# Constantes pour les noms des colonnes des données Actisense.
ACTISENSE: str = "Actisense"
"""Valeur de la constante pour le type de données Actisense."""
LINE_ACTISENSE: str = "Line"
"""Valeur de la constante pour la colonne de ligne des données Actisense."""
TIME_ACTISENSE: str = "Time"
"""Valeur de la constante pour la colonne de temps des données Actisense."""
NAME_ACTISENSE: str = "Name"
"""Valeur de la constante pour la colonne de nom des données Actisense."""
DEPTH_ACTISENSE: str = "Water Depth Transducer"
"""Valeur de la constante pour la colonne de profondeur des données Actisense."""
OFFSET_ACTISENSE: str = "Offset"
"""Valeur de la constante pour la colonne de décalage des données Actisense."""
POSITION_DATE_ACTISENSE: str = "Position date"
"""Valeur de la constante pour la colonne de date de position des données Actisense."""
POSITION_TIME_ACTISENSE: str = "Position time"
"""Valeur de la constante pour la colonne de temps de position des données Actisense."""
LATITUDE_ACTISENSE: str = "Latitude.1"
"""Valeur de la constante pour la colonne de latitude des données Actisense."""
LONGITUDE_ACTISENSE: str = "Longitude.1"
"""Valeur de la constante pour la colonne de longitude des données Actisense."""
COURSE_OVER_GROUND_ACTISENSE: str = "Course Over Ground"
"""Valeur de la constante pour la colonne de cap sur le fond des données Actisense."""
SPEED_OVER_GROUND_ACTISENSE: str = "Speed Over Ground"
"""Valeur de la constante pour la colonne de vitesse sur le fond des données Actisense."""
PGN_ACTISENSE: str = "PGN"
"""Valeur de la constante pour la colonne de PGN des données Actisense."""

# Constantes pour les noms des colonnes des données BlackBox.
BLACKBOX: str = "BlackBox"
"""Valeur de la constante pour le type de données BlackBox."""

# Constantes pour les dtypes des données.
FLOAT64: str = "float64"
"""Valeur de la constante pour le type de données float64."""
EPSG_WGS84: str = "EPSG:4326"
"""Valeur de la constante pour le code EPSG 4326."""

# Constantes pour les extensions de fichier.
EXTENSION_CSV: str = ".csv"
"""Valeur de la constante pour l'extension de fichier CSV."""
EXTENSION_XYZ: str = ".xyz"
"""Valeur de la constante pour l'extension de fichier XYZ."""
EXTENSION_TXT: str = ".TXT"
"""Valeur de la constante pour l'extension de fichier TXT."""
